### ISSUE TITLE
event.nodeIds data type inconsistency

### ISSUE THREAD

**Issue by fedosejev** [ImperialCollegeLondon/PhyloCanvas#22] opened 2014-07-09 12:32 UTC
When I listen to ```selected``` event, I get back ```event``` object with ```nodeIds``` property. If I select more than one node - ```nodeIds``` is an array. If I select just one node - ```nodeIds``` is a string.

To promote consistency, I think ```nodeIds``` should always be an array.

**Comment by jyothishnt** [comment] 2015-04-27 16:02
Duplicate of #68

**Closed by jyothishnt** 2015-04-27 16:02 UTC
